Update README.md
okta/okta-sdk-java pull request #573
Opened 2021-04-06 21:46 UTC by arvindkrishnakumar-okta

## Issue(s)

## Description

## Category

- [ ] Bugfix
- [ ] Enhancement
- [ ] New Feature
- [ ] Configuration Change
- [ ] Versioning Change
- [ ] Unit Test(s)
- [ ] Documentation

2021-04-06 21:49 UTC, bdemers approved these changes

2021-04-06 21:50 UTC, bdemers requested changes
Retire 3.x

2021-04-06 22:00 UTC, arvindkrishnakumar-okta commented
> Retire 3.x

I believe we have to support 3.x atleast for 9 months from the date of release. Correct me if I'm wrong here.

2021-04-06 22:18 UTC, bdemers approved these changes

2021-04-07 14:51 UTC, sergiishamrai-okta approved these changes

2021-04-07 21:01 UTC, merged