Migration guide for SDK v5.0.0
okta/okta-sdk-java pull request #589
Opened 2021-05-20 07:32 UTC by sergiishamrai-okta

## Category

- [x] Documentation

SDK supports openapi-spec v2.6.0
New Interfaces and Enums has been added.

2021-05-20 14:28 UTC, bdemers requested changes

2021-05-20 14:28 UTC, bdemers commented on MIGRATING.md
> +## Migrating from 4.x.x to 5.0.0
5.0 should be 4.1 ?

2021-05-20 14:50 UTC, bdemers commented
IMHO, this depends on #590 getting re-opened and merged first
cc: @arvindkrishnakumar-okta

2021-05-20 15:03 UTC, arvindkrishnakumar-okta commented
> IMHO, this depends on #590 getting re-opened and merged first
> cc: @arvindkrishnakumar-okta

Agreed.

2021-07-06 11:23 UTC, arvindkrishnakumar-okta requested changes
See open [comment](https://github.com/okta/okta-sdk-java/pull/589#issuecomment-845190386) above.

2021-07-15 16:10 UTC, arvindkrishnakumar-okta commented on MIGRATING.md
> +Version 5.0.0 of this SDK introduces a number of breaking changes from previous versions.
```suggestion
Version 4.1.x of this SDK introduces a number of breaking changes from previous versions.
```

2021-07-15 16:10 UTC, arvindkrishnakumar-okta requested changes
see comments.

2021-08-28 01:21 UTC, arvindkrishnakumar-okta approved these changes

2021-08-28 14:12 UTC, merged