Add a BOM for easier dependency management
okta/okta-sdk-java pull request #649
Opened 2021-10-02 13:07 UTC by jamietanna

## Issue(s)

N/A

## Description

To allow for easier managing of dependencies for consumers of the Okta
SDK, we can introduce a Bill of Materials (BOM).

## Category

- [ ] Bugfix
- [x] Enhancement
- [x] New Feature
- [ ] Configuration Change
- [ ] Versioning Change
- [ ] Unit Test(s)
- [ ] Documentation

2021-10-04 06:33 UTC, sergiishamrai-okta commented
Hi @jamietanna,
Thanks for the PR.
We'll investigate the necessity of such an approach and back to you.

2021-10-04 14:47 UTC, arvindkrishnakumar-okta commented
Thanks for the PR.

Request you to please sign the CLA at https://developer.okta.com/cla/

> On Oct 2, 2021, at 8:07 AM, Jamie Tanna ***@***.***> wrote:
> 
> ﻿
> This message originated outside your organization.
> 
> 
> 
> Issue(s)
> 
> N/A
> 
> Description
> 
> To allow for easier managing of dependencies for consumers of the Okta
> SDK, we can introduce a Bill of Materials (BOM).
> 
> Category
> 
>  Bugfix
>  Enhancement
>  New Feature
>  Configuration Change
>  Versioning Change
>  Unit Test(s)
>  Documentation
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/okta/okta-sdk-java/pull/649
> 
> Commit Summary
> 
> Add a BOM for easier dependency management
> File Changes
> 
> A bom/pom.xml (83)
> M pom.xml (1)
> Patch Links:
> 
> https://github.com/okta/okta-sdk-java/pull/649.patch
> https://github.com/okta/okta-sdk-java/pull/649.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-10-04 17:03 UTC, bdemers requested changes
Thanks @jamietanna!

We probably want to tweak this a little, probably remove the test, examples, and coverage modules.  Only the `api`, `impl`, and HTTP client libs _should_ be needed.  I usually recommend against using `project.version` (to avoid a few edge cases).

Taking a step back though, if we create a BOM, it _might_ be better to create a separate project and include all other related Okta libs, (SDK, Auth libs, JWT verifier, etc).

@jamietanna, I'm guessing you are using this SDK with another Okta lib and need to make sure the versions are aligned?  Or are you seeing version/dependency issues with other projects?

2021-10-04 17:16 UTC, jamietanna commented
Hey @bdemers thanks for the comments!

> Only the api, impl, and HTTP client libs should be needed.

Sure thing, I'll amend that :+1:

>  I usually recommend against using project.version (to avoid a few edge cases).

Interesting, what would be the alternative you'd recommend?

> Taking a step back though, if we create a BOM, it might be better to create a separate project and include all other related Okta libs, (SDK, Auth libs, JWT verifier, etc).

That's a very fair shout! Would it make sense to be here, or a completely fresh GitHub repo + standalone project?

>  I usually recommend against using project.version (to avoid a few edge cases).

On one of [my side projects](https://gitlab.com/jamietanna/www-api/) I've been using [WhiteSource Renovate](https://www.whitesourcesoftware.com/free-developer-tools/renovate/) and have found that it's raised a few MRs:

- https://gitlab.com/jamietanna/www-api/-/merge_requests/293
- https://gitlab.com/jamietanna/www-api/-/merge_requests/294
- https://gitlab.com/jamietanna/www-api/-/merge_requests/295

This isn't a problem, but it'd be even better if it could bump them all together through a BOM!

2021-10-04 17:30 UTC, bdemers commented
I'm guessing it would need to be a separate GitHub repo just to avoid circular dependencies, but maybe there is an alternative we can come up with.

As for the `project.version` usage. IIRC and this was from Maven 2 days, (so it's possible these issues have been resolved).  There are a few cases where `project.version` can be resolved to a different version than was originally intended, for example, if I created a project that extended from this bom AND used a new version. `project.version` could resolve to the new version.  

Again, it's been years since tracking that type of issue down, so i could be miss remembering the details too.  We use the Versions plugin (`versions:set -DnewVersion=<new-version-here>`) and it takes care of all of updating the nested versions too.

Also, the chances of someone using this as parent pom are very low, so I'm probably just a bit paranoid 🤣

2021-10-06 07:45 UTC, jamietanna commented
Thanks, I've amended the `project.version` :+1:

Thinking about it, I still feel like this should be added on its own - as well as having i.e. an `okta-platform:okta-platform-bom` which includes all of the Okta projects, having an easy way to just update the clients together makes sense, especially as we've got a monorepo that is versioned together - thoughts?

2021-10-06 15:25 UTC, jamietanna commented
This certainly does work (and the Gradle equivalents) but though this would be a quick way to solve it for consumers.

I'd be happy to get a PR raised to a repo if you can create one with an initial commit for me?

(I was hoping this would be a Hacktoberfest contribution, but happy to wait if it's gonna take a bit of time to get the thinking / versioning strategy right for everything)

2022-01-13 14:40 UTC, jamietanna commented
Hey folks, any thoughts as to whether we'd be happy creating a BOM for this library on its own, before we look at a wider one?

2022-01-13 15:15 UTC, sergiishamrai-okta commented
Hi @jamietanna ,
Thanks for PR. We'll review it shortly.

2022-01-17 09:24 UTC, sergiishamrai-okta commented
A “bom” project could be created, but that would need to include all of our Java libraries (and live in a separate git repo), so closing this PR for now and waiting for a decision about creating "bom" project with all Java libraries.

2022-01-17 09:24 UTC, closed without merging